channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.3.1
- pip:
  - mlflow==2.22.0
  - astunparse==1.6.3
  - cloudpickle==3.1.1
  - dill==0.3.8
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==6.1.1
  - scikit-learn==1.6.0
  - scipy==1.15.0
  - torch==2.7.0
  - tqdm==4.67.1
name: mlflow-env
